### ISSUE TITLE
Wishlist: Binary sensor, class update: Homepilot Update Available

### ISSUE THREAD

**Issue by hklages** [peribeir/homeassistant-rademacher#11]
Hi - 1.3.2 works fine and I am now replacing my HomePilot scenes rest_command by Home Assistant scenes: 
```
blinds_set_scene:
  url: "http://hkHomepilot.fritz.box/scenes/{{sid}}/actions"
  method: POST
  payload: '{ "request_type": "EXECUTESCENE", "trigger_event": "TRIGGER_SCENE_MANUALLY_EVT" }'
```

**So last open topic is:** 

For all my systems I monitor "status running", "recent backups done" and whether **"updates are available"**.
Is it possible to have the "update available" for the HomePilot 2 in you integration? 

Currently I do that with the following sensors: 
(HomePilot 2 is available at hkHomePilot.fritz.box = 192.168.178.15 - that is discovered by your integration (dhcp discovery))

in file binary sensor
```
- name:  "SHS Homepilot Update Available"
    state: "{{ state_attr('sensor.homepilot_update_and_version', 'update_status') != 'NO_UPDATE_AVAILABLE' }}"
    device_class: update

```	
in in configuration yaml: 
```
rest: 	
# SHS System Health Service: HomePilot get update and version as attributes every day
  - resource_template: "http://hkHomepilot.fritz.box/service/system-update-image/status"
    method: "GET"
    scan_interval: 86400
    sensor: 
      name: "HomePilot Update And Version"
      value_template: "{{ now() }}"
      json_attributes:
      - update_status
      - version
```

**Comment by hklages** [comment]
By the way, here is my list of Rademacher commands, compiled from different sources.
```

http://{{ipHomepilot}}/v4/devices/v4/devices
http://{{ipHomepilot}}/v4/devices?devtype=Sensor
http://{{ipHomepilot}}/v4/devices?devtype=Transmitter
http://{{ipHomepilot}}/v4/devices?devtype=Camera
http://{{ipHomepilot}}/v4/devices?devtype=Actuator
http://{{ipHomepilot}}/v4/devices/10002

http://{{ipHomepilot}}/v4/scenes
http://{{ipHomepilot}}/v4/scenes/5025

http://{{ipHomepilot}}/v4/groups/devicegroups
http://{{ipHomepilot}}/automation

http://{{ipHomepilot}}/service/system/networkmgr/v1/nodename
http://{{ipHomepilot}}/service/system/networkmgr/v1/interfaces
http://{{ipHomepilot}}/service/system/networkmgr/v1/interfaces/wlan0/ip_config
http://{{ipHomepilot}}/service/system/networkmgr/v1/interfaces/eth0/ip_config

http://{{ipHomepilot}}/service/system/leds/status

http://{{ipHomepilot}}/service/system-update-image/version
http://{{ipHomepilot}}/service/system-update-image/status

http://{{ipHomepilot}}/newdevices

http://{{ipHomepilot}}/service/system/twilight
```

```
set position:
  url: "http://{{ipHomepilot}}/devices/{{did}}"
  method: PUT
  content_type: "application/json; charset=utf-8"
  payload: '{"name": "GOTO_POS_CMD", "value": {{ (100 - position)|int }} }'

up:
    url: "http://{{ipHomepilot}}/devices/{{did}}"
    method: PUT
    payload: '{"name":"POS_UP_CMD"}'

down:
    url: "http://{{ipHomepilot}}/devices/{{did}}"
    method: PUT
    payload: '{"name":"POS_DOWN_CMD"}'

stop:
    url: "http://{{ipHomepilot}}/devices/{{did}}"
    method: PUT
    payload: '{"name":"STOP_CMD"}'

set scene:
  url: "http://{{ipHomepilot}}/scenes/{{sid}}/actions"
  method: POST
  payload: '{ "request_type": "EXECUTESCENE", "trigger_event": "TRIGGER_SCENE_MANUALLY_EVT" }'

backup - will also start a download so should be don in browser
 url: "http://{{ipHomepilot}}/service/system/backup/actions"
 method: POST
 payload: {"request_type":"STARTBACKUP"}
```
