### ISSUE TITLE
Rademacher item group in HA

### ISSUE THREAD

**Issue by Zeppelin-PV** [peribeir/homeassistant-rademacher#146]
hi,
i have Homepilot in HA running, and it works fine
today i want to add a group from Rademacher (3 lights) into HA
i cannot find the group in Rademacher entities
is there a way to add Rademacher groups and maybe also autmations ?

**Comment by oilid** [comment]
You have to add manually a group by YAML (groups.yaml):

```
alle_fenster_turkontakte_alarm:
  name: "Rademacher: Alle Fenster-/Türkontakte für den Alarm"
  entities:
    - sensor.sensor_kl_fenster_badezimmer_og_contact_state
    - sensor.sensor_fenster_gaste_wc_contact_state
    - sensor.sensor_fenster_gastezimmer_contact_state
    - sensor.sensor_fenster_kuche_contact_state
    - sensor.sensor_fenster_wohnzimmer_contact_state
    - sensor.sensor_terrassentur_esszimmer_contact_state
    - sensor.sensor_terrassentur_wohnzimmer_contact_state
    - sensor.sensor_fenster_hwr_contact_state
```

Then you can use the entity: _group.alle_fenster_turkontakte_alarm_
