### ISSUE TITLE
No issue, just for your information

### ISSUE THREAD

**Issue by hklages** [peribeir/homeassistant-rademacher#28]
Hi. In case you would like to see the HomePilot in your Home Assistatn side menu you could add the following data to configuration yaml. You have to replace the url with your ipv4 address or DNS name.
One restriction: Using the the ling, the backup does not work. 

```
# Panel HomePilot, external address
panel_iframe:
  homepilot:
    title: "HomePilot"
    url: "http://hkHomepilot.fritz.box"
    icon: mdi:window-shutter
```
![sidebar](https://user-images.githubusercontent.com/17273119/154225491-2389455c-3e4d-4f36-bc7e-02a59efd659d.jpg)
