### ISSUE TITLE
Delay when operating Shutters

### ISSUE THREAD

**Issue by deltaphi** [peribeir/homeassistant-rademacher#91]
I use a Rademacher HomePilot Gateway to control electric shutter motors around the house. For a long time, I used a really old version of this Plugin which worked fine. A few weeks ago I Updated to v1.13.1. Things are still mostly fine, however: I have scripts set up in Home Assistant to operate multiple (all) shutters at once. On the old version, this made all Shutters move at the same time. On v1.13.1, the Shutters start moving with a significant delay (10 to 20 seconds, perhaps? I didn't actually pull out a stop watch).

I have not changed anything about my gateway or my scripts. I just do regular updates of my Home Assistant installation and did the aforementioned update of the Rademacher Add-On - the change happened right after the update.

What can I do to make the shutters move all at the same time again?

**Comment by peribeir** [comment]
Hi @deltaphi 
I don't see any change that could have caused that change in behavior.
Do you remember which version you had before the update?
Also can you share your script?

**Comment by deltaphi** [comment]
I was previously using 4459c62f674573d878e7c0f11090f7fab4ffb2aa.

The script I'm using is this (abbreviated to three covers):

```
alias: Rolläden Rademacher zu
sequence:
  - device_id: 2c3701331e1821a24fbb849d4a7eb76e
    domain: cover
    entity_id: 3cb266c9e36b8956247d0ea67b3615d5
    type: close
  - device_id: 4407760214d5309ce7e1e1a170bb3bc0
    domain: cover
    entity_id: 4c6f32748261df5e81140b67e9398602
    type: close
  - device_id: 141c46ce1b117d2d7d145a9fadad9a8c
    domain: cover
    entity_id: b6c9cdd9632d4b4627903fbf4b292c1a
    type: close
mode: restart
icon: mdi:window-shutter
```

**Comment by bash-public-willpower** [comment]
I can confirm that the shutters do not move at the same time but one after another with a delay of maybe ten seconds. v1.13.1 is the first version I was ever using so I cannot say if it was otherwise before.

**Comment by rhmunich** [comment]
I had a similar experience. It appears that HomePilot waits until the first shutter confirms that completed the task and just then sends out the second task.
I fixed it by using the `parallel ` function in Home Assistant. With this, it works just fine.

Would appreciate your feedback if you find another or better solution.

Your script would look then like this:

```
alias: Rolläden Rademacher zu
sequence:
  - parallel:
      - device_id: 2c3701331e1821a24fbb849d4a7eb76e
        domain: cover
        entity_id: 3cb266c9e36b8956247d0ea67b3615d5
        type: close
      - device_id: 4407760214d5309ce7e1e1a170bb3bc0
        domain: cover
        entity_id: 4c6f32748261df5e81140b67e9398602
        type: close
      - device_id: 141c46ce1b117d2d7d145a9fadad9a8c
        domain: cover
        entity_id: b6c9cdd9632d4b4627903fbf4b292c1a
        type: close
mode: restart
icon: mdi:window-shutter
```
